### ISSUE TITLE
Having issues

### ISSUE THREAD

**Issue by mikep809** [sunnysyed/viper_smart_start_lambda#1]
Hi

I need help completing the skill..

Stuck after skill url from the viper smartstart skill setup point.  Then certificate endpoint.

Greatly appreciated 

Thxs 
Mike

**Comment by sunnysyed** [comment]
@mikep809 I need more information what exactly are you trying to do and where are you stuck?

**Comment by mikep809** [comment]
Hi Sunny

stuck after the Region. so the url ? then the certification?  
thxs
Mike

**Comment by mikep809** [comment]
Hi Sunny 

please help, want to work this out.

Greatly appreciate it!

thxs Mike

**Comment by mikep809** [comment]
Hi Sunny

ok i figured it out, but the skill doesnt execute. please help don't mind at all contributing a donation if I can get this to work..


thxs Mike appreciate the help!

**Comment by sunnysyed** [comment]
Have you uploaded this as a lambda function on aws? 
Follow this to create the lambda function and test https://docs.aws.amazon.com/lambda/latest/dg/get-started-create-function.html
The payload required is { "email": "email@email.com", "password": "password", "command": "REMOTE" }

**Comment by mikep809** [comment]
Hi Sunny

totally lost can you script this for me, this is my very first time. no clue here . I'll gladly contribute for your time 

Regards.
Mike

**Comment by sunnysyed** [comment]
https://www.youtube.com/watch?v=tDJ_a0uJqPI

Follow that video to create a lambda skill sub code for the code posted in lambda.py

**Comment by mikep809** [comment]
dude I have to hand it to you. this is a very long process. can wrap my hands on this.

**Comment by mikep809** [comment]
hi Sunny

is it possible you to script it like you did the skill?

Again I will compensate you.

thxs
Mike

**Comment by mikep809** [comment]
Hi Sunny

Need your help dude. I hate using the smartstart app. it's not convenient at all. I spoke to DIRECTED they have no plan to release a skill. I looked at the YouTube video cant follow. I greatly appreciate your help. this is my personal email dukkiep@aol.com.  greatly appreciate it.
